version: '2'

services:
  nginx: 
    restart: unless-stopped
    build:
        context: .
        dockerfile: ./docker/nginx/Dockerfile
    ports:
        - 80:80
    volumes:
        - static_volume:/app/backend/build
        - ./docker/nginx:/etc/nginx/conf.d
    depends_on: 
        - django
  django:
    restart: unless-stopped
    build:
        context: .
        dockerfile: ./docker/django/Dockerfile
    entrypoint: /app/backend/wsgi-entrypoint.sh
    volumes:
        - static_volume:/app/backend/build
    expose:
        - 8080
    env_file:
      - ./.env.prod

volumes:
  static_volume: {}

networks:
  default:
    external:
      name: leds-network
