version: '2'

services:
  nginx: 
    restart: unless-stopped
    build:
        context: .
        dockerfile: ./docker/nginx/Dockerfile
    image:
        gradrix/leds_web_nginx
    ports:
        - 80:80
    volumes:
        - ./frontend-build:/usr/share/nginx/html:rw
    depends_on: 
        - django
  django:
    restart: unless-stopped
    build:
        context: .
        dockerfile: ./docker/django/Dockerfile
    image:
        gradrix/leds_web_django
    entrypoint: /app/wsgi-entrypoint.sh
    volumes:
        - ./web/config:/app/config
        - ./frontend-build:/frontend-build:rw
    expose:
        - 8080
    env_file:
      - ./.env.prod

networks:
  default:
    external:
      name: leds-network
