# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: led_service.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'led_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11led_service.proto\x1a\x1bgoogle/protobuf/empty.proto\"r\n\x11GetStatusResponse\x12\r\n\x05is_on\x18\x01 \x01(\x08\x12\x12\n\nbrightness\x18\x02 \x01(\x05\x12\r\n\x05speed\x18\x03 \x01(\x05\x12\x0c\n\x04mode\x18\x04 \x01(\x05\x12\x0e\n\x06toggle\x18\x05 \x01(\x05\x12\r\n\x05\x63olor\x18\x06 \x01(\t\"T\n\x0fGetModeResponse\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\r\n\x05index\x18\x02 \x01(\x05\x12\x11\n\tmin_speed\x18\x03 \x01(\x05\x12\x11\n\tmax_speed\x18\x04 \x01(\x05\"#\n\x12ToogleOnOffRequest\x12\r\n\x05is_on\x18\x01 \x01(\x08\"1\n\x17\x43hangeBrightnessRequest\x12\x16\n\x0enew_brightness\x18\x01 \x01(\x05\"%\n\x11\x43hangeModeRequest\x12\x10\n\x08new_mode\x18\x01 \x01(\x05\".\n\x18\x43hangeToggleValueRequest\x12\x12\n\nnew_toggle\x18\x01 \x01(\x05\"\'\n\x12\x43hangeSpeedRequest\x12\x11\n\tnew_speed\x18\x01 \x01(\x05\"\'\n\x12\x43hangeColorRequest\x12\x11\n\tnew_color\x18\x01 \x01(\t2\xb7\x04\n\nLedControl\x12\x37\n\tGetStatus\x12\x16.google.protobuf.Empty\x1a\x12.GetStatusResponse\x12\x33\n\x07GetMode\x12\x16.google.protobuf.Empty\x1a\x10.GetModeResponse\x12?\n\rResetSettings\x12\x16.google.protobuf.Empty\x1a\x16.google.protobuf.Empty\x12:\n\x0bToogleOnOff\x12\x13.ToogleOnOffRequest\x1a\x16.google.protobuf.Empty\x12\x44\n\x10\x43hangeBrightness\x12\x18.ChangeBrightnessRequest\x1a\x16.google.protobuf.Empty\x12\x38\n\nChangeMode\x12\x12.ChangeModeRequest\x1a\x16.google.protobuf.Empty\x12\x46\n\x11\x43hangeToggleValue\x12\x19.ChangeToggleValueRequest\x1a\x16.google.protobuf.Empty\x12:\n\x0b\x43hangeSpeed\x12\x13.ChangeSpeedRequest\x1a\x16.google.protobuf.Empty\x12:\n\x0b\x43hangeColor\x12\x13.ChangeColorRequest\x1a\x16.google.protobuf.Emptyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'led_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GETSTATUSRESPONSE']._serialized_start=50
  _globals['_GETSTATUSRESPONSE']._serialized_end=164
  _globals['_GETMODERESPONSE']._serialized_start=166
  _globals['_GETMODERESPONSE']._serialized_end=250
  _globals['_TOOGLEONOFFREQUEST']._serialized_start=252
  _globals['_TOOGLEONOFFREQUEST']._serialized_end=287
  _globals['_CHANGEBRIGHTNESSREQUEST']._serialized_start=289
  _globals['_CHANGEBRIGHTNESSREQUEST']._serialized_end=338
  _globals['_CHANGEMODEREQUEST']._serialized_start=340
  _globals['_CHANGEMODEREQUEST']._serialized_end=377
  _globals['_CHANGETOGGLEVALUEREQUEST']._serialized_start=379
  _globals['_CHANGETOGGLEVALUEREQUEST']._serialized_end=425
  _globals['_CHANGESPEEDREQUEST']._serialized_start=427
  _globals['_CHANGESPEEDREQUEST']._serialized_end=466
  _globals['_CHANGECOLORREQUEST']._serialized_start=468
  _globals['_CHANGECOLORREQUEST']._serialized_end=507
  _globals['_LEDCONTROL']._serialized_start=510
  _globals['_LEDCONTROL']._serialized_end=1077
# @@protoc_insertion_point(module_scope)
